package app/compoents/admin/funcionario;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class FuncionarioComponent extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Funcionario funcionario;
	

	
		
	
		
	
	
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void save() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void delete() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
	
	
	/** Getter for funcionario. */
	public Funcionario getFuncionario() {
		return funcionario;
	}

	/** Setter for funcionario. */
	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}
	

}