package br.ufes.informatica.jurisproc.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Funcionario extends PersistentObjectSupport implements Comparable<Funcionario> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String codigo;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private Integer idade;







	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for codigo. */
	public String getCodigo() {
		return codigo;
	}
	
	/** Setter for codigo. */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/** Getter for idade. */
	public Integer getIdade() {
		return idade;
	}
	
	/** Setter for idade. */
	public void setIdade(Integer idade) {
		this.idade = idade;
	}








	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Funcionario o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}