package br.ufes.informatica.jurisproc.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Nota extends PersistentObjectSupport implements Comparable<Nota> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String conteudo;







	/** Getter for conteudo. */
	public String getConteudo() {
		return conteudo;
	}
	
	/** Setter for conteudo. */
	public void setConteudo(String conteudo) {
		this.conteudo = conteudo;
	}








	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Nota o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}