package components/NovoUsuario;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class NovoUsuarioComponent extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Usuario usuario;
	

	
		
	
	
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void salvarNovoUsuario() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
	
	
	/** Getter for usuario. */
	public Usuario getUsuario() {
		return usuario;
	}

	/** Setter for usuario. */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	

}