package components;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class LvItemNota extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Nota nota;
	

	
		
	
	
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void apagar() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
	
	
	/** Getter for nota. */
	public Nota getNota() {
		return nota;
	}

	/** Setter for nota. */
	public void setNota(Nota nota) {
		this.nota = nota;
	}
	

}