package components;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class LvNovaNota extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String estado;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String conteudo;
	

	
		
	
	
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void criar() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
	
	
	/** Getter for estado. */
	public String getEstado() {
		return estado;
	}

	/** Setter for estado. */
	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	/** Getter for conteudo. */
	public String getConteudo() {
		return conteudo;
	}

	/** Setter for conteudo. */
	public void setConteudo(String conteudo) {
		this.conteudo = conteudo;
	}
	

}