package app/components/admin/departamento;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class DepartamentoComponent extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Departamento departamento;
	

	
		
	
		
	
	
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void save() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
		
			/** TODO: generated by FrameWeb. Should be documented. */
			public void delete() {
				// FIXME: auto-generated method stub
				return;
			}
		
	
	
	
	/** Getter for departamento. */
	public Departamento getDepartamento() {
		return departamento;
	}

	/** Setter for departamento. */
	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}
	

}